all_joints:
- - 0
- - 1
- - 2
- - 3
- - 4
- - 5
- - 6
- - 7
- - 8
- - 9
- - 10
- - 11
- - 12
- - 13
- - 14
- - 15
- - 16
- - 17
- - 18
- - 19
- - 20
- - 21
- - 22
- - 23
- - 24
- - 25
all_joints_names:
- C1_Left_1
- C1_Left_2
- C1_Left_3
- C1_Left_4
- C1_Left_5
- C1_Right_5
- C1_Right_4
- C1_Right_3
- C1_Right_2
- C1_Right_1
- Eye_Left_1
- Eye_Left_2
- Eye_Left_3
- Eye_Left_4
- Eye_Left_5
- Eye_Left_6
- Eye_Right_1
- Eye_Right_2
- Eye_Right_3
- Eye_Right_4
- Eye_Right_5
- Eye_Right_6
- Mid_1
- Mid_2
- Mid_3
- Snout
batch_size: 1
bottomheight: 400
crop: true
cropratio: 0.4
dataset: training-datasets\iteration-2\UnaugmentedDataSet_Whisking_with_MidlineMay3\Whisking_with_Midline_Frank
  Ma95shuffle1.mat
dataset_type: default
display_iters: 1000
global_scale: 0.8
init_weights: C:\Users\NA659\AppData\Local\Continuum\anaconda3\envs\DLC-GPU-FM\lib\site-packages\deeplabcut\pose_estimation_tensorflow\models\pretrained\resnet_v1_50.ckpt
intermediate_supervision: false
intermediate_supervision_layer: 12
leftwidth: 400
location_refinement: true
locref_huber_loss: true
locref_loss_weight: 0.05
locref_stdev: 7.2801
max_input_size: 1500
metadataset: training-datasets\iteration-2\UnaugmentedDataSet_Whisking_with_MidlineMay3\Documentation_data-Whisking_with_Midline_95shuffle1.pickle
min_input_size: 64
minsize: 100
mirror: false
multi_step:
- - 0.005
  - 10000
- - 0.02
  - 430000
- - 0.002
  - 730000
- - 0.001
  - 1030000
net_type: resnet_50
num_joints: 26
pos_dist_thresh: 17
project_path: C:\Users\JI712\OneDrive - Tufts\Jobs\SPEL\Whisking\Whisking_with_Midline-Frank
  Ma-2020-05-03
rightwidth: 400
save_iters: 50000
scale_jitter_lo: 0.5
scale_jitter_up: 1.25
topheight: 400
